### ISSUE TITLE
%player_name% appear everywhere

### ISSUE THREAD

**Issue by XNarno** [Pliexe/DiscordEconomyBridge#1]
When I do some commands (with slash or prefix), It doesn't show correctly names and show "%player_name%" ^^'
PS: I'm using it with DiscordSRV I don't know if that count ^^'

![image](https://user-images.githubusercontent.com/74362225/152030962-378dfb9a-53a5-4bf1-80c8-c247251e70a3.png)

**Comment by Pliexe** [comment]
Do you use Placeholder api?

**Comment by Pliexe** [comment]
If placeholder api is detected it won't attempt to replace these placeholders and in these case you would need to get the appropriate placeholder for player.
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#player

**Comment by XNarno** [comment]
Okay It works I didn't understand this part ^^'
Thank you ^^

(I had to make /papi ecloud download Player)
