### ISSUE TITLE
Coinflip thief

### ISSUE THREAD

**Issue by XNarno** [Pliexe/DiscordEconomyBridge#2]
I love all the game but I noticed a bug with the coinflip.

First, I think all the player have to accept the coinflip, because my players are able to thief money to other players.
If player A has 500 000 and player B has 400 000, player B coinflip player A with a wager of 400 000 and win, player A is ruined even if he don't want to play the game.

Second thing is player is able to create money with coinflip.
If Player A coinflip player B with 500 000 and win, player A will have 1 000 000 but player B will have 400 000 because the plugin can't remove him 500 000 so in this case, 500 000 of money is created ^^'

**Comment by Pliexe** [comment]
I can't believe I missed this so hard. :O I think it's time to sleep my sleep schedule and not do this at night, I'll get it fixed when I get home from English exam!

**Comment by Pliexe** [comment]
Should be fixed in 2.1
https://github.com/Pliexe/DiscordEconomyBridge/commit/6e226c4e0ac7740739227449b5559fde2b6ed549
