### ISSUE TITLE
Bug with coinflip acceptation.

### ISSUE THREAD

**Issue by XNarno** [Pliexe/DiscordEconomyBridge#3]
When we use coinflip against another person, if the person accept the buttons won't disappear and the person can accept many times he wants, and every accept is a new game so if the person A win the first game, person B can re-click on accept and win too.

Another thing is if the person B decline, he can re-accept and re-decline so he can use the button everytime.

**Comment by Pliexe** [comment]
Am actually aware of this, as I scouted the code before but I wanted to release the fix with a another fix that I couldn't get working so I'll just release the current fix I guess.
