### ISSUE TITLE
Custom commands issues

### ISSUE THREAD

**Issue by Proxwian** [Pliexe/DiscordEconomyBridge#7]
I've tried to change default "work" command to another word and it stopped working

Also I've tried to set cooldown for "work" command and it also doesn't work

Cooldown for custom command with the same logic and custom name also no luck

Also custom command, I've tried to create doesn't work in discord bot

Tested on Spigot@1.18.2

**Comment by Proxwian** [comment]
nvm, restart helps

**Comment by Pliexe** [comment]
Currently, custom commands are being completely redone.
